language: rust
cache: cargo

rust:
  - stable

matrix:
  include:
    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - chmod +x ./ci/install_cargo_web.sh
  - ./ci/install_cargo_web.sh
  - cargo test --target $TARGET --verbose --release
  - cargo web build --example alpha --release
  - cargo web build --example basic --release
  - cargo web build --example blit --release
  - cargo web build --example demo --release
  - cargo web build --example exit --release
  - cargo web build --example fonts --release
  - cargo web build --example image --release
  - cargo web build --example perf --release
  - cargo web build --example resize --release
  - cargo web build --example subcell --release
  - cargo web build --example text_input --release
  - cargo web build --example unicode --release
