language: rust
cache: cargo

rust:
  - nightly

matrix:
  include:
    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  - ./ci/install_cargo_web.sh
  - cargo build --target $TARGET --verbose
  - cargo build --target $TARGET --verbose --examples
  - cargo web build --example basic
  - cargo web build --example basic --release
