[package]
name = "doryen-rs"
version = "0.1.0"
authors = ["jice <jice.nospam@gmail.com>"]

[workspace]

[dependencies]
webgl = {git="https://github.com/unrust/webgl"}
uni-app = {git="https://github.com/unrust/uni-app"}

[dependencies.image]
version = "0.19.0"
default-features = false
features = ["png_codec"]

[features]
