[package]
name = "doryen-rs"
version = "0.1.0"
authors = ["jice <jice.nospam@gmail.com>"]

[workspace]

[dependencies]
webgl = {git="https://github.com/unrust/webgl"}
#uni-app = {git="https://github.com/unrust/uni-app"}
uni-app = {git="https://github.com/IvoWingelaar/uni-app", branch="glutin-0.17-upgrade" }
uni-glsl = {git="https://github.com/unrust/uni-glsl"}

[dependencies.image]
version = "0.19.0"
default-features = false
features = ["png_codec"]

[features]
